### ISSUE TITLE
Limit the total results that will be paginated?

### ISSUE THREAD

**Issue by FranciscoCG** [mislav/will_paginate#519] opened 2017-01-26 01:46 UTC
Is there a way to limit the total results that will be paginated?

Ex:
@posts = Post.paginate(:page => params[:page])
p.count = 1000000
per_page = 10
Total_links = 1000000/10 = 100000

will result in a total of 100000 links into views.

We need to be able to do:

@search_items = Post.search "milk", page: params[:page], per_page: 10, total_entries: 1000

This works ok if I do it with AR:
@search_items = Post.paginate(page:1, per_page:10, total_entries:1000)

**Comment by mattrothstein** [comment] 2017-02-08 04:55
@FranciscoCG  You need to call paginate on your collection after your query.

```ruby 
@search_items = Post.search("milk").paginate(page: params[:page], per_page: 10, total_entries: 1000)
```

**Comment by mislav** [comment] 2021-05-10 09:11
Duplicate of https://github.com/mislav/will_paginate/issues/476

**Closed by mislav** 2021-05-10 09:11 UTC
