### ISSUE TITLE
undefined method `total_pages' for #<Review::ActiveRecord_Relation:0x00000005979ac8>): 

### ISSUE THREAD

**Issue by Denswami** [mislav/will_paginate#557] opened 2017-10-28 13:32 UTC
Hello,

I get this error in production,(Heroku) but will paginate works fine in development mode on local machine, what could be the issue? Please help

**Comment by mislav** [comment] 2021-05-09 13:51
Duplicate of https://github.com/mislav/will_paginate/issues/411#issuecomment-835809901

**Closed by mislav** 2021-05-09 13:51 UTC
