### ISSUE TITLE
undefined method total_pages error total_pages for #<Comment::ActiveRecord_AssociationRelation:0x47f7540>

### ISSUE THREAD

**Issue by ghost** [mislav/will_paginate#575] opened 2018-06-11 21:42 UTC
Hi, I’m having an issue with getting the ‘will_paginate’ gem to work. Here is the site I’m working on - https://kevin-meldau-my-test-store.herokuapp.com/products. This is the error I keep getting - https://snag.gy/BqEGAi.jpg

**This is how I’ve loaded the gem:**
1.	Added 'will_paginate', '~> 3.1.0' to my gem file then run bundle
2.	Added this to my products controller:

def show
@comments = @product.comments.order("created_at DESC")
@comments = @product.comments.paginate(page: params[:page], per_page: 5)
end

3.	Then added this to my show.html.erb file:

<%= will_paginate @comments %>

**Any help would be greatly appreciated! All the best, Kevin**

**Comment by timkrins** [comment] 2018-06-19 11:55
Maybe try

    def show
      @comments = @product.comments
        .order(created_at: :desc)
        .paginate(page: params[:page], per_page: 5, total_pages: @product.comments.count)
    end

Might be something to do with the way your relation is configured on the product.

**Comment by mislav** [comment] 2021-05-10 10:11
Duplicate of https://github.com/mislav/will_paginate/issues/411#issuecomment-835809901

**Closed by mislav** 2021-05-10 10:11 UTC
