### ISSUE TITLE
Upgrading to 3.1.0 from 3.0.7 overrides the i18n translations in our app

### ISSUE THREAD

**Issue by soma** [mislav/will_paginate#475] opened 2016-03-17 14:27 UTC
Hello!

We just upgraded from 3.0.7 to the latest version 3.1.0, and our application has yml files that specifies how the pagination should be translated. Previous version worked as desired, our translations were used. But in this last update the "default" translations was used instead of our ones.

**Comment by henrik** [comment] 2016-03-18 08:18
Same team as @soma. Some more details:

We have YML files like

``` yml
en:
  will_paginate:
    next_label: ►
    page_gap: "&hellip;"
    previous_label: ◄
```

After this upgrade, pages in our default locale (English) stopped showing our custom "◄" etc and instead showed the built-in defaults, "<- Previous page" or something like that. But pages in another locale (Swedish) did show our custom text.

**Comment by jgarber623** [comment] 2016-03-18 23:18
This is related to (or a duplicate of) #466.

**Comment by mislav** [comment] 2016-09-21 09:51
Closing as duplicate

**Closed by mislav** 2016-09-21 09:51 UTC
